# Generated by Django 5.2.15 on 2026-06-03 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_assignment_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('assignment_description', models.TextField(blank=True)),
                ('points_possible', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('require_manual_approval', models.BooleanField(default=True)),
                ('workflow_state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grading.coursesync')),
            ],
            options={
                'unique_together': {('course', 'canvas_assignment_id')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_submission_id', models.BigIntegerField()),
                ('canvas_user_id', models.BigIntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('submission_type', models.CharField(blank=True, max_length=50)),
                ('submission_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('canvas_workflow_state', models.CharField(blank=True, max_length=64)),
                ('ai_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], default='pending', max_length=20)),
                ('proposed_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proposed_feedback', models.TextField(blank=True)),
                ('final_feedback', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.assignmentconfig')),
            ],
            options={
                'unique_together': {('assignment', 'canvas_submission_id')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('attachment', 'Attachment'), ('online_url', 'Online URL')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='grading.submissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasPostAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_attempts', to='grading.submissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('instructor_username', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to='grading.submissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AIFeedbackDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('draft_feedback', models.TextField()),
                ('draft_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='grading.submissionrecord')),
            ],
        ),
    ]
